spring:
  application:
     name: quotes-service
pivotal:
  quotes:
    quote_url: https://cloud.iexapis.com/stable/stock/{symbol}/quote?token=pk_3447c6aeb21b40ce99367a5b37b2aacd
    quotes_url: https://cloud.iexapis.com/stable/stock/market/batch?symbols={symbols}&types=quote&token=pk_3447c6aeb21b40ce99367a5b37b2aacd
    companies_url: http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}

